version: '3.7'

x-networks:
  &default-networks
  networks:
    - memorization_net

x-env:
  &default-env
  env_file:
    - .env

x-volumes:
  &default-volumes
  volumes:
    - memorization_media:/srv/memorization_media
    - memorization_static:/srv/memorization_static

x-app:
  &default-app
  build: .
  <<: *default-volumes
  <<: *default-env
  <<: *default-networks

services:
  db:
    image: postgres:14.6-alpine
    container_name: db
    restart: always
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=${DBPASSWORD}
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_DB=${DBNAME}
    <<: *default-env
    <<: *default-networks

  web:
    <<: *default-app
    command: bash nginx_configs/gunicorn.sh
    links:
      - "db:db"
      - "memorization_redis:memorization_redis"
    expose:
      - "8000"
    depends_on:
      - db
      - memorization_redis

  nginx:
    build: ./nginx_configs/nginx/
    restart: always
    expose:
      - "80"
    ports:
      - "80:80"
    links:
      - "web:web"
    depends_on:
      - web
    volumes:
      - memorization_media:/srv/memorization_files/media/
      - memorization_static:/srv/memorization_files/static/
    <<: *default-networks

  memorization_redis:
    image: redis:alpine
    container_name: memorization_redis
    # command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    expose:
      - "6379"
    <<: *default-networks

  celery:
    <<: *default-app
    restart: always
    command: celery -A memorization_backend worker -l info -B
    depends_on:
      - web
      - memorization_redis

  celery-beat:
    <<: *default-app
    restart: always
    command: celery -A memorization_backend beat -l info
    links:
      - memorization_redis
    depends_on:
      - web
      - memorization_redis

volumes:
  pgdata:
  memorization_media:
  memorization_static:


networks:
  memorization_net:
