# Generated by Django 4.1.5 on 2023-01-20 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Text we want to remember")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SECOND_REPEAT", "SECOND_REPEAT"),
                            ("THIRD_REPEAT", "THIRD_REPEAT"),
                            ("FOURTH_REPEAT", "FOURTH_REPEAT"),
                            ("DONE", "DONE"),
                        ],
                        default="SECOND_REPEAT",
                        max_length=50,
                        verbose_name="Execution status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_reminders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Execution status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reminder",
                "verbose_name_plural": "Reminders",
            },
        ),
    ]
